name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.tag_name || github.ref }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x playscore/gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build Release APK
      run: cd playscore && ./gradlew assembleRelease
      
    - name: Build Debug APK
      run: cd playscore && ./gradlew assembleDebug
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v7
      with:
        name: playscore-release-apk
        path: playscore/app/build/outputs/apk/release/*.apk
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v7
      with:
        name: playscore-debug-apk
        path: playscore/app/build/outputs/apk/debug/*.apk
        
    - name: Upload APKs to Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/') || inputs.tag_name
      with:
        tag_name: ${{ inputs.tag_name || github.ref_name }}
        files: |
          playscore/app/build/outputs/apk/release/*.apk
          playscore/app/build/outputs/apk/debug/*.apk